export const API_ENDPOINT = {
  REQUEST_OTP: 'authen/request-otp',
  FORGOT_PW_OTP: 'authen/forgot-password-otp',
  FORGOT_PW: 'authen/forgot-password',
  VERIFY_OTP: 'authen/verify-otp',
  CREATE_USER: 'authen/create-user',
  LOGIN: 'authen/login',
  LOGOUT: 'authen/logout',
  GET_PROFILE: 'authen/profile',
  GET_SESSION: 'authen/get-session',
  DRIVERS_CITY: 'group_driver',
  DRIVER_DETAIL: 'group_driver_detail',
  CREATE_CHAT_ROOM: 'chat-room/create',
  DRIVER_REACT: 'drive/react',
  GET_LIST_CHAT_BY_USER: 'chat-room/get-by-user',
  GET_MESSAGE_BY_USER: 'chat/user-get-messages',
  GET_MESSAGE_IMAGE: 'chat/send-files',
  PICK_TICKET: 'drive/pick',
  DRIVE: 'drive',
  DRIVE_UPDATE_STATUS: 'drive/update-status',
  DRIVE_UPDATE: 'drive/update',
  DRIVE_RATING: 'drive/rating',
  JOIN_GROUP: 'group-driver-detail/join-group',
  SET_NOTIFICATION: 'group_driver_detail/set_notification',
  NEWS: 'news',
  UPDATE_PROFILE: 'user/update',
  TRANSACTION: 'transaction',
  STATISTIC: 'statistic',
  UTILS: 'utils',
  USER_REQUEST: 'user-request',
  CHANGE_PASSWORD: 'user/change-password',
  SEARCH_MESSAGE: 'chat/search-messages',
  NOTIFICATION: 'notification',
  NUMBER_NOTIFICATION: 'notification/unread',
  // DETAIL_NOTIFICATION: 'notification/:id ',
};
