export const Images = {
  splash: require('./splash.json'),
  logo: require('./logo.png'),
  default_image: require('./default-image.png'),
  flash_01: require('./flash_01.png'),
  flash_02: require('./flash_02.png'),
  flash_03: require('./flash_03.png'),
  flash_04: require('./flash_04.png'),
  flash_05: require('./flash_05.png'),
  image20: require('./image20.png'),
  driver: require('./driver.png'),
  hd_user: require('./hd_user.png'),
  ic_user: require('./user.jpg'),
  transaction_bg: require('./transaction_bg.png'),
  img_delete_account: require('./img_delete_account.png'),
  ic_vietcombank: require('./ic_vietcombank.png'),
  ic_viettinbank: require('./ic_viettinbank.png'),
  ic_visa: require('./ic_visa.png'),
  ic_master_card: require('./ic_master_card.png'),
  ic_jcb: require('./ic_jcb.png'),
  ic_napas: require('./ic_napas.png'),
  ic_alepay: require('./ic_alepay.png'),
  ic_zalopay: require('./ic_zalopay.png'),
  ic_momo: require('./ic_momo.png'),
  logo_vietcombank: require('./logo_vietcombank.png'),
  logo_vietinbank: require('./logo_vietinbank.png'),
  intro_01: require('./intro_01.jpg'),
  intro_02: require('./intro_02.jpg'),
  intro_03: require('./intro_03.jpg'),
  // iconDots_vertical: require('./iconDots_vertical'),
};
