/**
 * @description define the navigation routes name by key
 */
export const Routes: {[key: string]: string} = {
  Login: 'Login',
  Register: 'Register',
  Intro: 'Intro',
  HomeTabs: 'HomeTabs',
  Profile: 'Profile',
  Home: 'Home',
  Account: 'Account',
  Statistic: 'Statistic',
  Transaction: 'Transaction',
  OTP: 'OTP',
  KYC: 'KYC',
  ResetPassword: 'ResetPassword',
  InputPassword: 'InputPassword',
  ResearchFn: 'ResearchFn',
  SponsoredList: 'SponsoredList',
  SponsoredDetail: 'SponsoredDetail',
  ListDriver: 'ListDriver',
  GroupDriverDetail: 'GroupDriverDetail',
  DriverCustom: 'DriverCustom',
  ChatDetail: 'ChatDetail',
  ChatCustom: 'ChatCustom',
  Chat: 'Chat',
  ListChat: 'ListChat',
  ProvinceList: 'ProvinceList',
  Vote: 'Vote',
  DriveDetail: 'DriveDetail',
  MemberList: 'MemberList',
  RequestDelete: 'RequestDelete',
  Contact: 'Contact',
  AccountInfo: 'AccountInfo',
  Policy: 'Policy',
  Term: 'Term',
  ChangePassword: 'ChangePassword',
  BalanceInfo: 'BalanceInfo',
  Recharge: 'Recharge',
  RequestSupport: 'RequestSupport',
  BankTransfer: 'BankTransfer',
  Notification: 'Notification',
};
